[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.nox
  | \.pytest_cache
  | \.venv
  | build
  | dist
  | logs
  | outputs
)/
'''
