echo "--- WRemnants"
source ../WRemnants/setup.sh
echo
echo "--- WRemnantsHelpers"
export MY_WORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export MY_PLOT_DIR="/home/submit/$USER/public_html/alphaS/"
export MY_OUT_DIR="/ceph/submit/data/group/cms/store/user/$USER/alphaS/"
export NANO_DIR="/scratch/submit/cms/wmass/NanoAOD/"
export SCRATCH_DIR="/scratch/submit/cms/alphaS/"
export PATH="$MY_WORK_DIR/bin:$PATH"
echo "Added $MY_WORK_DIR/bin to PATH"
echo "Created environment variable MY_WORK_DIR=$MY_WORK_DIR"
echo "Created environment variable MY_PLOT_DIR=$MY_PLOT_DIR"
echo "Created environment variable MY_OUT_DIR=$MY_OUT_DIR"
echo "Created environment variable NANO_DIR=$NANO_DIR"
echo "Created environment variable SCRATCH_DIR=$SCRATCH_DIR"