#!/bin/bash
set -e
source /opt/venv/bin/activate
cd /home/submit/lavezzo/alphaS/WRemnantsHelpers
source setup.sh > /dev/null 2>&1 || true
echo "BEGIN_SEQ $(date)"
echo "=== START pdf_mb $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_pdf_mb_inclusive --freezeParameters mb_up 'pdfMSHT20mbrange.*'
echo "=== END pdf_mb $(date) ==="
echo "=== START pdfCT18Z $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_pdfCT18Z_inclusive --freezeParameters 'pdf\d+CT18Z.*'
echo "=== END pdfCT18Z $(date) ==="
echo "=== START pdf_mb_and_CT18Z $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_pdf_mb_and_CT18Z_inclusive --freezeParameters mb_up 'pdfMSHT20mbrange.*' 'pdf\d+CT18Z.*'
echo "=== END pdf_mb_and_CT18Z $(date) ==="
echo "=== START scetlibNP $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_scetlibNP_inclusive --freezeParameters '.*scetlibNP.*' 'chargeVgenNP.*'
echo "=== END scetlibNP $(date) ==="
echo "=== START resumTNP $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_resumTNP_inclusive --freezeParameters 'resumTNP_.*'
echo "=== END resumTNP $(date) ==="
echo "=== START prefire_stat $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_prefire_stat_inclusive --freezeParameters 'CMS_prefire_stat_.*'
echo "=== END prefire_stat $(date) ==="
echo "=== START pixel_multiplicity $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_pixel_multiplicity_inclusive --freezeParameters 'pixel_multiplicity_.*'
echo "=== END pixel_multiplicity $(date) ==="
echo "=== START fsr_photos $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_fsr_photos_inclusive --freezeParameters 'horacelophotos.*' '.*FSR.*'
echo "=== END fsr_photos $(date) ==="
echo "=== START qcdscale_helicity $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_qcdscale_helicity_inclusive --freezeParameters 'QCDscaleZfine_.*'
echo "=== END qcdscale_helicity $(date) ==="
echo "=== START all_top_suspects $(date) ==="
/home/submit/lavezzo/alphaS/main/WRemnants/rabbit/bin/rabbit_fit.py /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0//ZMassDilepton.hdf5 --computeVariations -m Project ch0 ptll yll -m Project ch0 ptll -m Project ch0 yll -m Project ch0 cosThetaStarll_quantile -m Project ch0 phiStarll_quantile --computeHistErrors --computeHistImpacts --doImpacts -o /ceph/submit/data/group/cms/store/user/lavezzo/alphaS//260429_fitAlphaSRapidityDecorr/ZMassDilepton_ptll_yll_cosThetaStarll_quantile_phiStarll_quantile_nominal_LambdaScale5p0/ --globalImpacts --saveHists --saveHistsPerProcess --blindingGroup '^.*AlphaS.*$' -v 4 -t 0 --fullNll --postfix freeze_all_top_suspects_inclusive --freezeParameters mb_up 'pdfMSHT20mbrange.*' 'pdf\d+CT18Z.*' '.*scetlibNP.*' 'chargeVgenNP.*' 'resumTNP_.*' 'CMS_prefire_stat_.*' 'pixel_multiplicity_.*' 'horacelophotos.*' '.*FSR.*' 'QCDscaleZfine_.*'
echo "=== END all_top_suspects $(date) ==="
echo "DONE_SEQ_OK $(date)"
